/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 8987cb208a1ce3ced6dcfaa6aede3bd8)
interface __BaseEnv_CloudflareEnv {
	UPLOADS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	NEXTJS_ENV: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV" | "SESSION_SECRET">> {}
}
