#!/usr/bin/env node
/**
 * One-time data migration: export the old MongoDB data as SQL for Cloudflare D1
 * and dump uploaded files for Cloudflare R2.
 *
 * Usage:
 *   npm i --no-save mongodb
 *   MONGODB_URI="mongodb+srv://..." node scripts/mongo-to-d1.mjs
 *
 * Produces:
 *   mongo-export/data.sql            -> wrangler d1 execute rate-calculator-db --remote --file=mongo-export/data.sql
 *   mongo-export/uploads/*           -> raw uploaded files
 *   mongo-export/upload-to-r2.sh     -> bash mongo-export/upload-to-r2.sh  (pushes files to R2)
 *
 * Document _ids are preserved (ObjectId hex strings), so records keep their
 * user associations. Everything is idempotent-ish: INSERT OR REPLACE is used.
 */
import { mkdirSync, writeFileSync, appendFileSync, chmodSync } from "node:fs";
import path from "node:path";

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error("Set MONGODB_URI, e.g. MONGODB_URI='mongodb+srv://...' node scripts/mongo-to-d1.mjs");
  process.exit(1);
}

let MongoClient;
try {
  ({ MongoClient } = await import("mongodb"));
} catch {
  console.error("The 'mongodb' driver is not installed. Run: npm i --no-save mongodb");
  process.exit(1);
}

const OUT_DIR = path.resolve("mongo-export");
const UPLOADS_DIR = path.join(OUT_DIR, "uploads");
mkdirSync(UPLOADS_DIR, { recursive: true });

const sqlFile = path.join(OUT_DIR, "data.sql");
writeFileSync(sqlFile, "-- Generated by scripts/mongo-to-d1.mjs\nPRAGMA defer_foreign_keys = on;\n");

/** SQL literal helpers */
const S = (v) => (v === null || v === undefined ? "NULL" : `'${String(v).replaceAll("'", "''")}'`);
const N = (v) => (v === null || v === undefined || Number.isNaN(Number(v)) ? "0" : String(Number(v)));
const B = (v) => (v ? "1" : "0");
const DATE = (v) => {
  if (!v) return "NULL";
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? "NULL" : `'${d.toISOString()}'`;
};
const ID = (v) => (v ? `'${String(v)}'` : "NULL");
const J = (v) => S(JSON.stringify(v ?? null));

const client = new MongoClient(MONGODB_URI);
await client.connect();
const db = client.db();

let statements = 0;
function emit(sql) {
  appendFileSync(sqlFile, sql + "\n");
  statements++;
}

// ---- users ----
const users = await db.collection("users").find({}).toArray();
for (const u of users) {
  emit(
    `INSERT OR REPLACE INTO users (_id, stuntlistingUserId, email, firstName, lastName, tier, role, lastLogin, stlAccessToken, createdAt, updatedAt) VALUES (` +
      [
        ID(u._id),
        S(u.stuntlistingUserId ?? String(u._id)),
        S(u.email ?? ""),
        S(u.firstName ?? ""),
        S(u.lastName ?? ""),
        S(u.tier ?? "free"),
        S(u.role ?? "user"),
        DATE(u.lastLogin),
        S(u.stlAccessToken ?? null),
        DATE(u.createdAt ?? new Date()),
        DATE(u.updatedAt ?? new Date()),
      ].join(", ") +
      ");"
  );
}
console.log(`users: ${users.length}`);

// ---- work records ----
const workRecords = await db.collection("workrecords").find({}).toArray();
for (const r of workRecords) {
  emit(
    `INSERT OR REPLACE INTO work_records (_id, userId, workType, otherWorkCategory, showName, workDate, callTime, dismissOnSet, dismissMakeupWardrobe, ndMealIn, ndMealOut, firstMealStart, firstMealFinish, secondMealStart, secondMealFinish, stuntAdjustment, forcedCall, isSixthDay, isSeventhDay, isHoliday, workStatus, characterName, notes, recordStatus, documents, calculation, paymentStatus, paidAmount, paidDate, expectedAmount, paymentDueDate, missingExhibitG, photos, createdAt, updatedAt) VALUES (` +
      [
        ID(r._id),
        ID(r.userId),
        S(r.workType ?? "sag_aftra"),
        S(r.otherWorkCategory ?? null),
        S(r.showName ?? ""),
        DATE(r.workDate ?? new Date()),
        S(r.callTime ?? null),
        S(r.dismissOnSet ?? null),
        S(r.dismissMakeupWardrobe ?? null),
        S(r.ndMealIn ?? null),
        S(r.ndMealOut ?? null),
        S(r.firstMealStart ?? null),
        S(r.firstMealFinish ?? null),
        S(r.secondMealStart ?? null),
        S(r.secondMealFinish ?? null),
        N(r.stuntAdjustment),
        B(r.forcedCall),
        B(r.isSixthDay),
        B(r.isSeventhDay),
        B(r.isHoliday),
        S(r.workStatus ?? null),
        S(r.characterName ?? ""),
        S(r.notes ?? ""),
        S(r.recordStatus ?? "complete"),
        S(JSON.stringify(r.documents ?? [])),
        r.calculation ? J(r.calculation) : "NULL",
        S(r.paymentStatus ?? "unpaid"),
        N(r.paidAmount),
        DATE(r.paidDate),
        N(r.expectedAmount),
        DATE(r.paymentDueDate),
        B(r.missingExhibitG),
        S(JSON.stringify(r.photos ?? [])),
        DATE(r.createdAt ?? new Date()),
        DATE(r.updatedAt ?? new Date()),
      ].join(", ") +
      ");"
  );
}
console.log(`work_records: ${workRecords.length}`);

// ---- residual imports + checks ----
const residualImports = await db.collection("residualimports").find({}).toArray();
let checkCount = 0;
for (const imp of residualImports) {
  emit(
    `INSERT OR REPLACE INTO residual_imports (_id, userId, performerName, filename, totalChecks, totalGross, createdAt, updatedAt) VALUES (` +
      [
        ID(imp._id),
        ID(imp.userId),
        S(imp.performerName ?? "Unknown Performer"),
        S(imp.filename ?? ""),
        N(imp.totalChecks ?? (imp.checks?.length ?? 0)),
        N(imp.totalGross),
        DATE(imp.createdAt ?? new Date()),
        DATE(imp.updatedAt ?? new Date()),
      ].join(", ") +
      ");"
  );
  (imp.checks ?? []).forEach((c, i) => {
    checkCount++;
    emit(
      `INSERT OR REPLACE INTO residual_checks (_id, importId, seq, sagAftraId, payeeName, payeeType, company, payrollHouse, productionTitle, checkStatus, checkStatusDate, checkNumber, checkDate, grossAmount, netAmount, receivedDate, donated, prodTitleGrossAmt) VALUES (` +
        [
          ID(c._id ?? `${imp._id}-${i}`),
          ID(imp._id),
          String(i),
          S(c.sagAftraId ?? ""),
          S(c.payeeName ?? ""),
          S(c.payeeType ?? ""),
          S(c.company ?? ""),
          S(c.payrollHouse ?? ""),
          S(c.productionTitle ?? "Unknown"),
          S(c.checkStatus ?? ""),
          S(c.checkStatusDate ?? ""),
          S(c.checkNumber ?? ""),
          S(c.checkDate ?? ""),
          N(c.grossAmount),
          N(c.netAmount),
          S(c.receivedDate ?? ""),
          S(c.donated ?? ""),
          N(c.prodTitleGrossAmt),
        ].join(", ") +
        ");"
    );
  });
}
console.log(`residual_imports: ${residualImports.length} (${checkCount} checks)`);

// ---- uploads (binary files -> R2) ----
const uploads = await db.collection("uploads").find({}).toArray();
const r2Script = path.join(OUT_DIR, "upload-to-r2.sh");
writeFileSync(r2Script, "#!/usr/bin/env bash\nset -euo pipefail\ncd \"$(dirname \"$0\")\"\n");
for (const up of uploads) {
  const data = up.data?.buffer ?? up.data; // BSON Binary -> Buffer
  if (!data) continue;
  writeFileSync(path.join(UPLOADS_DIR, up.filename), Buffer.from(data));
  appendFileSync(
    r2Script,
    `npx wrangler r2 object put "rate-calculator-uploads/${up.filename}" --remote --file="uploads/${up.filename}" --content-type "${up.contentType ?? "application/octet-stream"}"\n`
  );
}
chmodSync(r2Script, 0o755);
console.log(`uploads: ${uploads.length} file(s) written to ${UPLOADS_DIR}`);

await client.close();

console.log(`\nWrote ${statements} SQL statements to ${sqlFile}`);
console.log("\nNext steps:");
console.log("  1. npx wrangler d1 execute rate-calculator-db --remote --file=mongo-export/data.sql");
console.log("  2. bash mongo-export/upload-to-r2.sh");
